name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # toastification: ^1.2.0
  get_it: ^7.6.7
  responsive_sizer: ^3.3.0+1
  supabase_flutter: ^2.3.4
  timeago: ^3.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/illustrations/login.png
    - assets/images/profile.jpg
  uses-material-design: true
